### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by egorzakharov** [CelebV-HQ/CelebV-HQ#10]
Hello!

Thanks for sharing the dataset, I am sure it will benefit a lot of future works in the area of human video synthesis!

I have noticed that you did not include the license for the videos in your materials. Is it possible to include the type of license which every video is shared on YouTube into the metadata? I believe that a default YT license prohibits the download from the website unless explicit permission from the authors was obtained, while some of the videos in your dataset may have CC license and can be legally used.

We would like to use your dataset in our works, but also would want to avoid using copyrighted content. Thanks!

**Comment by sunshineatnoon** [comment]
Hi, is there any update on the license? We would also like to release a model trained on this dataset, knowing the license would help a lot. Thanks!

**Comment by zhuhaozh** [comment]
Hi, sorry for the late reply. 

We don't own the rights to any of these videos. Please comply with the youtube license, that would be fine. 

For the metadata, which are produced by human annotators based on online videos and not include any sensitivitive information. Free feel to use these data we provided, and we're not planning to add a specific license to these data.
