### ISSUE TITLE
What is the whole dataset size?

### ISSUE THREAD

**Issue by wmpscc** [CelebV-HQ/CelebV-HQ#5]
Thank you very much for your team's contribution. How much is disk storage required for the complete dataset?

**Comment by simongfxu** [comment]
Less than 3TB, not including tailored videos.

**Comment by caopulan** [comment]
> Less than 3TB, not including tailored videos.

Are you sure? I have downloaded 30,000 files (including some audio files which have not been merged) and require 3.5T now.

**Comment by simongfxu** [comment]
> > Less than 3TB, not including tailored videos.
> 
> Are you sure? I have downloaded 30,000 files (including some audio files which have not been merged) and require 3.5T now.

According to the JSON file, the number of unique youtube ids is less than 15000.

**Comment by caopulan** [comment]
> > > Less than 3TB, not including tailored videos.
> > 
> > 
> > Are you sure? I have downloaded 30,000 files (including some audio files which have not been merged) and require 3.5T now.
> 
> According to the JSON file, the number of unique youtube ids is less than 15000.

You are right, I'm going to check it again.

**Comment by wmpscc** [comment]
Actually, the YouTube IDS is more than 30000. And why is the file so big after 30000? It even averages over 1GB per video.

**Comment by zhuhaozh** [comment]
If you try to keep the original youtube video, the storage requirement will be very large. But you can delete the original video that you will not use later. The final processed video should be <100GB.

**Comment by wmpscc** [comment]
Thank you, I will check it. @zhuhaozh
