### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by jackjtjt** [CelebV-HQ/CelebV-HQ#6]
Thank you very much for your project.
I had some problems when running it, it appear as shown in the below, I tried but couldn't fix it. Do you know any information about this?

**[youtube] 8VZctic_uTI: Downloading android player API JSON
ERROR: [youtube] 8VZctic_uTI: Requested format is not available. Use --list-formats for a list of available formats
video not found: 8VZctic_uTI
yt-dlp --proxy 127.0.0.1:10809 -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --skip-unavailable-fragments --merge-output-format mp4 https://www.youtube.com/watch?v=iBrravwJQ1Q --output ./downloaded_celebvhq/raw/iBrravwJQ1Q.mp4 --external-downloader aria2c --external-downloader-args "-x 16 -k 1M"
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[youtube] iBrravwJQ1Q: Downloading webpage
[youtube] iBrravwJQ1Q: Downloading android player API JSON
ERROR: [youtube] iBrravwJQ1Q: Requested format is not available. Use --list-formats for a list of available formats
video not found: iBrravwJQ1Q
yt-dlp --proxy 127.0.0.1:10809 -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --skip-unavailable-fragments --merge-output-format mp4 https://www.youtube.com/watch?v=ow0x7MuH9iA --output ./downloaded_celebvhq/raw/ow0x7MuH9iA.mp4 --external-downloader aria2c --external-downloader-args "-x 16 -k 1M"
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[youtube] ow0x7MuH9iA: Downloading webpage
[youtube] ow0x7MuH9iA: Downloading android player API JSON**

**Comment by wywu** [comment]
#8 may help.

**Comment by lancel-nv** [comment]
Please upgrade the yt-dlp, like you could directly download latest package here.
https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2024.07.25.232820
